### ISSUE TITLE
usergroup topic rights

### ISSUE THREAD

**Issue by actimeo** [actimeo/simmage-backend#17]
Depends on #15
- [x] Add an enum type login.usergroup_topic_right (similar to login.user_right) with these values: event_read, event_add, event_update
- [x] add a column login.usergroup_topic.ust_rights, type login.usergroup_topic_right[]
- [x] adapt procedures
- [x] adapt tests

**Comment by JeremyB-EPSI** [comment]
- [ ] Add revelent example data in mecs.php file
