### ISSUE TITLE
Individual / grouped dossier and patient / external dossier

### ISSUE THREAD

**Issue by feloy** [actimeo/simmage-backend#4]
Define a dossier as 
- individual or grouped
- patient or external

- [x] add a boolean column 'dos_grouped' to organ.dossier
- [x] add a boolean column 'dos_external' to organ.dossier
- [x] add a text column 'dos_groupname' to organ.dossier
- [x] add constraints so firstname & lastname are not null and groupname is null when grouped is false  
- [x] add constraints so firstname & lastname are null and groupname not null when grouped is true
- [x] add a function dossier_add_individual(token, firstname, lastname, birthdate, is_external)
- [x] add a function dossier_add_grouped(token, groupname, is_external)

**Comment by JeremyB-EPSI** [comment]
add a function to update individual dossier fields (with check if not grouped dossier)
